version: '2.1'

orbs:
  heroku: circleci/heroku@2.0.0
  node: circleci/node@5.1.0

jobs:
  build-and-test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install
      - run:
          command: npm install
          name: Install dependencies
      - run:
          command: npm run test
          name: Run tests
  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run:
          name: Deploy app to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main

workflows:
  main:
    jobs:
      - build-and-test
      - deploy:
          force: true # this parameter instructs the push to use a force flag when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git
          requires:
            - build-and-test
